modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "simplyimprovedterrain"
version = "${version}"
displayName = "Simply Improved Terrain"
authors = "K.jpg"
description = '''
Rewrites terrain generation components in Minecraft to improve their visual results.
'''
#logoFile = ""

[[dependencies.simplyimprovedterrain]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplyimprovedterrain]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
