org.gradle.jvmargs=-Xmx6G

minecraft_version=1.20.1
enabled_platforms=quilt,fabric,forge

archives_base_name=Simply-Improved-Terrain
mod_version=1.20.1-0.5.6.0-alpha
maven_group=jpg.k

fabric_loader_version=0.14.21
fabric_api_version=0.83.0+1.20.1

forge_version=1.20.1-47.0.18

quilt_loader_version=0.19.1
quilt_fabric_api_version=7.0.3+0.83.1-1.20.1

# Dependencies
mixinextras_version = 0.5.0-beta.5
