org.gradle.jvmargs=-Xmx6G

minecraft_version=1.21.1
enabled_platforms=quilt,fabric,forge,neoforge

archives_base_name=Simply-Improved-Terrain
mod_version=1.21.1-0.5.6.1-alpha
maven_group=jpg.k

fabric_loader_version=0.16.10
fabric_api_version=0.114.0+1.21.1

forge_version=1.21.1-52.0.40

neoforge_version = 21.1.84

quilt_loader_version=0.28.0-beta.6
quilt_fabric_api_version=11.0.0-alpha.3+0.102.0-1.21

# Dependencies
mixinextras_version = 0.5.0-beta.5
