org.gradle.jvmargs=-Xmx6G

minecraft_version=1.19.2
enabled_platforms=quilt,fabric,forge

archives_base_name=Simply-Improved-Terrain
mod_version=1.19.2-0.5.6.0-alpha
maven_group=jpg.k

fabric_loader_version=0.14.25
fabric_api_version=0.76.1+1.19.2

forge_version=1.19.2-43.3.2

quilt_loader_version=0.21.2-beta.2
quilt_fabric_api_version=4.0.0-beta.30+0.76.0-1.19.2

# Dependencies
mixinextras_version = 0.5.0-beta.5
joml_version = 1.10.8
