modLoader="javafml"
loaderVersion="[34,)"
license="MIT License"
issueTrackerURL="https://github.com/KdotJPG/Simply-Improved-Terrain/issues"

[[mods]]

modId="simplyimprovedterrain"
version="0.3.2-Forge"
displayName="Simply Improved Terrain"
logoFile="simplyimprovedterrain.png"
authors="K.jpg"

# The description text for the mod (multi line!) (#mandatory)
description='''
Simply Improved Terrain rewrites some of the terrain generation components in Minecraft to improve their visual results, while preserving the overall Vanilla impression. Specifically, it focuses on reworking directionally-biased, chunk-biased, or otherwise strongly-artificial-looking features. This mod is designed as a drop-in with intent for it to be compatible with many modpacks and datapacks. It is also intended to serve as a suggestion to Mojang regarding the technical direction they should take world generation.

Changes included:
- Replaces trilinear interpolation with conditional noise layer skipping, to make full-resolution noise practical. Also removes problematic high-frequency layers. This eliminates the majority of the grid patterns from the terrain.
- Replaces unmitigated Perlin noise with domain-rotated noise, to remove Perlin's characteristic 45-90-degree bias from the horizontal worldplane. This solves the direction variety problem without requiring as much re-tuning as the canonical solution of using Simplex-type noise.
- Re-implements terrain noise "shelves" in a way that localizes height, accounts for domain rotation, and doesn't require interpolation for smoothing.
- Injects domain-rotation into existing unmitigated Perlin noise, so that other features can also take advantage.
- Replaces the gradient vectors in 2D Simplex noise (used for surface block patterns) with a lattice-symmetric 24-sized set which reduces 45-degree artifacts.
- Replaces End Island generation with full-resolution jittered metaballs, to remove grid patterns and allow intersecting islands to merge more nicely.
- Introduces radius variation to the disk-shaped sand/gravel/clay/ice deposits, to make them more convincing. Also removes the sharp points. Idea credit: Origin Realms.
- Replaces Overworld biome transition smoothing with scattered sampling, to conceal the underlying 4x4-interval grid. Also makes rivers wider to avoid constrictions.
- Removes directional bias from the netherrack patterns below ruined portal structures, by replacing the |Δx|+|Δz| falloff with a Euclidean-based falloff.

Planned future changes:
- Rewrite Overworld biome map generation to remove or reduce large-scale directional bias, while following the same layer-based ruleset.
- Replace octahedral-shaped block deposits (particularly in the Nether) with less directionally-biased alternatives.
- Remove directional bias from the netherrack patterns in portal ruins, by replacing the square/diamond-shaped falloff with euclidean falloff.
- Improve the shapes of the isolated lake and lava pool features.

'''

[[dependencies.simplyimprovedterrain]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.simplyimprovedterrain]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="SERVER"
