modLoader="javafml"
loaderVersion="[34,)"
license="MIT License"
issueTrackerURL="https://github.com/KdotJPG/Simply-Improved-Terrain/issues"

[[mods]]

modId="simplyimprovedterrain"
version="0.3.3-Forge"
displayName="Simply Improved Terrain"
logoFile="simplyimprovedterrain.png"
authors="K.jpg"

# The description text for the mod (multi line!) (#mandatory)
description='''
Simply Improved Terrain rewrites some of the terrain generation components in Minecraft to improve their visual results, while preserving the overall Vanilla impression. Specifically, it focuses on increasing directional variety, grid independence, and overall feature variation. This mod is designed as a drop-in with intent for it to be compatible with many modpacks and datapacks.

Technical Changes:
- Replaces trilinear interpolation with dynamic noise layer skipping to make full-resolution noise practical. Also removes problematic high-frequency layers. This eliminates the majority of the grid patterns from the terrain.
- Replaces unmitigated Perlin noise with domain-rotated noise, to remove the algorithm's characteristic 45-90-degree bias from the horizontal worldplane. This solves the direction variety problem in mid-scale terrain shapes with less re-tuning than the canonical solution of using Simplex-type noise.
- Re-implements terrain noise "shelves" in a way that localizes height, accounts for domain rotation, and doesn't require interpolation for smoothing.
- Injects domain-rotation into existing unmitigated noise, so that other features can also take advantage.
- Replaces the gradient vectors in 2D Simplex noise (used for surface block patterns) with a lattice-symmetric 24-sized set which reduces 45-degree artifacts.
- Replaces End Island generator with full-resolution jittered metaballs to remove grid patterns, and allow intersecting islands to merge more nicely.
- Removes sharp points from the disk-shaped sand/gravel/clay/ice deposits to make them more convincing. Also adds radius variation. Idea credit: Origin Realms.
- Replaces Overworld biome transition smoothing with scattered sampling to conceal the underlying 4x4-interval grid. Also makes rivers wider to avoid constrictions.
- Removes directional bias from the netherrack patterns below ruined portal structures by replacing the `|Δx|+|Δz|` falloff with a Euclidean-based falloff.

'''

[[dependencies.simplyimprovedterrain]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.simplyimprovedterrain]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="SERVER"
