modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT-0 License"

[[mods]]
modId = "simplyimprovedterrain"
version = "${version}"
displayName = "Simply Improved Terrain"
authors = "K.jpg"
description = '''
Rewrites terrain generation components to improve their visual results.
'''

[[dependencies.simplyimprovedterrain]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplyimprovedterrain]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "simplyimprovedterrain-common.mixins.json"
